# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/admin/api.json"
  swaggerPath: "/admin/swagger"
  DumpRouterMap: true
  # 【关键】在这里添加 OpenApi 配置
  OpenApi:
        # 启用 OpenApi 功能
        Enabled: true
        # 自定义 Swagger UI 的访问路径，可选，默认为 "/swagger/"
        Path: "/admin/swagger"
        # 自定义 API JSON 文档的访问路径，可选，默认为 "/api.json"
        ApiPath:  "/admin/api.json"
        # (可选) 是否在生产环境中禁用
        # DisabledWhenProd: true

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"