// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file

import (
	"github.com/Soltus/encv-go/pkg/admin/api/file"
)

type ControllerV1 struct {
	servingDir string
}

func NewV1(servingDir string) file.IFileV1 {
	return &ControllerV1{
		servingDir: servingDir,
	}
}
