package main

import (
	"context"
	"time"

	openai "github.com/sashabaranov/go-openai"
)

// httpContext returns a context with a 30-second deadline, the
// default for the OpenList tool calls. The deadline is large
// enough to absorb the typical small-list operation without
// firing in normal use.
func httpContext() context.Context {
	ctx, _ := context.WithTimeout(context.Background(), 30*time.Second)
	return ctx
}

// OpenList tool schemas. Each is a small
// `*openai.FunctionDefinition` (a type alias) that the agent
// passes through to OpenAI as part of the function-calling
// request. The fields are intentionally minimal — the agent
// does not invent constraints the LLM could not satisfy.
//
// The schemas follow the OpenAI function-calling JSON Schema
// subset: top-level "type": "object" + properties + required.
var openListListFilesSchema = openai.FunctionDefinition{
	Name:        "list_files",
	Description: "列出 OpenList 远端目录下的文件。返回 name/size/is_dir/modified 字段。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"path": map[string]any{
				"type":        "string",
				"description": "OpenList 远端目录绝对路径（以 / 开头）",
			},
		},
		"required": []string{"path"},
	},
}

var openListReadFileSchema = openai.FunctionDefinition{
	Name:        "read_file",
	Description: "读取 OpenList 远端文件的文本内容。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"path": map[string]any{"type": "string"},
		},
		"required": []string{"path"},
	},
}

var openListWriteFileSchema = openai.FunctionDefinition{
	Name:        "write_file",
	Description: "将文本内容写入 OpenList 远端文件（覆盖模式）。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"path":    map[string]any{"type": "string"},
			"content": map[string]any{"type": "string"},
		},
		"required": []string{"path", "content"},
	},
}

var openListDeleteFileSchema = openai.FunctionDefinition{
	Name:        "delete_file",
	Description: "删除 OpenList 远端文件（需要用户确认）。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"path": map[string]any{"type": "string"},
		},
		"required": []string{"path"},
	},
}

var openListRenameSchema = openai.FunctionDefinition{
	Name:        "rename",
	Description: "重命名/移动 OpenList 远端文件（需要用户确认）。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"src": map[string]any{"type": "string"},
			"dst": map[string]any{"type": "string"},
		},
		"required": []string{"src", "dst"},
	},
}

var openListExecCommandSchema = openai.FunctionDefinition{
	Name:        "exec_command",
	Description: "在 OpenList 服务端执行一个 shell 命令（需要用户确认）。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"command": map[string]any{"type": "string"},
		},
		"required": []string{"command"},
	},
}

var openListGetStorageInfoSchema = openai.FunctionDefinition{
	Name:        "get_storage_info",
	Description: "返回 OpenList 存储的 total/used/free 字节数。",
	Parameters: map[string]any{
		"type":       "object",
		"properties": map[string]any{},
	},
}

var openListSearchFilesSchema = openai.FunctionDefinition{
	Name:        "search_files",
	Description: "在 OpenList 远端 parent 目录下按关键词搜索文件。",
	Parameters: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"parent":  map[string]any{"type": "string"},
			"keyword": map[string]any{"type": "string"},
		},
		"required": []string{"parent", "keyword"},
	},
}

// pluginSchemaPlaceholder is a deliberately minimal schema
// used by the demo's stub plugin tools. The real plugin tools
// are generated by `scanPluginTools` against the actual
// encv-go plugin set.
var pluginSchemaPlaceholder = openai.FunctionDefinition{
	Name:        "plugin_tool_placeholder",
	Description: "Plugin tool placeholder (real schema generated by scanPluginTools).",
	Parameters: map[string]any{
		"type":       "object",
		"properties": map[string]any{},
	},
}
